---
- name: Playbook to create docker image and push it to DockerHub on Ansible Server
  hosts: localhost
  become: true

  vars:
    image_name: "kanchakamanupriya/xyztechnologies"
    image_tag: "v2"
    dockerfile_path: "/opt/war_file"
    dockerhub_username: "kanchakamanupriya"

  tasks:

   - name: Remove existing image
     command: docker image rm "{{ image_name }}":"{{ image_tag }}"
     ignore_errors: yes

   - name: Build docker image
     community.docker.docker_image:
        build:
          path: "{{ dockerfile_path }}"
        name: "{{ image_name }}"
        tag: "{{ image_tag }}"
        push: true
        source: build
     register: out
   - debug:
        var: out



- name: Playbook to pull docker image from DockerHub and deploy it on Tomcat server
  hosts: tomcat

  vars:
    image_name: "kanchakamanupriya/xyztechnologies"
    image_tag: "latest"
    dockerhub_username: "kanchakamanupriya"
    container_name: "xyztechnologies-ansible-deploy"

  tasks:
    - name: Stop existing container
      community.docker.docker_container:
        name: "{{ container_name }}"
        state: stopped
      ignore_errors: yes

    - name: Remove existing container
      community.docker.docker_container:
        name: "{{ container_name }}"
        state: absent
      ignore_errors: yes

    - name: Remove existing image
      community.docker.docker_image:
        name: "{{ image_name }}"
        tag: "{{ image_tag }}"
        state: absent
      ignore_errors: yes

    - name: Pull docker image
      community.docker.docker_image:
        name: "{{ image_name }}"
        tag: "{{ image_tag }}"
        source: pull

    - name: Deploy the container to Tomcat server
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ image_name }}:{{ image_tag }}"
        state: started
        ports:
          - "8092:8080"




- name: Deploy to Kubernetes
  hosts: kubemaster
  become: true
  tasks:

    # - name: Delete existing Kubernetes Pod
    #   kubernetes.core.k8s:
    #     state: absent
    #     kubeconfig: /etc/kubernetes/admin.conf
    #     definition: "{{ lookup('file', 'pod.yml') }}"

    # - name: Delete existing Kubernetes Service
    #   kubernetes.core.k8s:
    #     state: absent
    #     kubeconfig: /etc/kubernetes/admin.conf
    #     definition: "{{ lookup('file', 'service.yml') }}"

    # - name: Delete existing Kubernetes Deployment
    #   kubernetes.core.k8s:
    #     state: absent
    #     kubeconfig: /etc/kubernetes/admin.conf
    #     definition: "{{ lookup('file', 'deployment.yml') }}"


    - name: Create Kubernetes Pod
      kubernetes.core.k8s:
        state: present
        kubeconfig: /etc/kubernetes/admin.conf
        definition: "{{ lookup('file', 'pod.yml') }}"

    - name: Create Kubernetes Service
      kubernetes.core.k8s:
        state: present
        kubeconfig: /etc/kubernetes/admin.conf
        definition: "{{ lookup('file', 'service.yml') }}"

    - name: Create Kubernetes Deployment
      kubernetes.core.k8s:
        state: present
        kubeconfig: /etc/kubernetes/admin.conf
        definition: "{{ lookup('file', 'deployment.yml') }}"




