apiVersion: apps/v1
kind: Deployment
metadata:
  name: xyztechnologies-deployment
  namespace: default
spec:
  replicas: 3
  minReadySeconds: 60
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: xyztechnologies
  template:
    metadata:
      labels:
        app: xyztechnologies
    spec:
      containers:
      - name: xyztechnologies-container
        image: kanchakamanupriya/xyztechnologies:v3
        ports:
        - containerPort: 8080
