apiVersion: v1
kind: Service
metadata:
  name: xyztechnologies-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: xyztechnologies
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30700 